import { StyleSheet } from '@react-pdf/renderer'

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    padding: 40,
    color: '#2C1810',
    backgroundColor: '#FEFAF0',
  },
  header: { marginBottom: 20 },
  academyName: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: '#8B1A1A',
  },
  academyTagline: { fontSize: 9, color: '#6B6B6B', marginTop: 2 },
  academyAddress: { fontSize: 8, color: '#6B6B6B', marginTop: 2 },
  reportTitle: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    marginTop: 16,
    marginBottom: 4,
    color: '#2C1810',
  },
  goldDivider: {
    borderBottomWidth: 2,
    borderBottomColor: '#D4AF37',
    marginVertical: 12,
  },
  thinDivider: {
    borderBottomWidth: 0.5,
    borderBottomColor: '#D4D0C8',
    marginVertical: 8,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 6,
    marginTop: 14,
    color: '#8B1A1A',
  },
  table: { width: '100%' },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#2C1810',
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  tableHeaderCell: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: '#FEFAF0',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: '#D4D0C8',
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  tableRowAlt: {
    backgroundColor: '#F5F0E8',
  },
  tableCell: { fontSize: 9, color: '#2C1810' },
  totalRow: {
    flexDirection: 'row',
    backgroundColor: '#D4AF37',
    paddingVertical: 7,
    paddingHorizontal: 8,
    marginTop: 2,
  },
  totalCell: { fontSize: 10, fontFamily: 'Helvetica-Bold', color: '#2C1810' },
  summaryBox: {
    backgroundColor: '#F5F0E8',
    padding: 12,
    borderRadius: 4,
    borderLeftWidth: 3,
    borderLeftColor: '#D4AF37',
    marginBottom: 16,
  },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 3 },
  summaryLabel: { fontSize: 9, color: '#6B6B6B' },
  summaryValue: { fontSize: 9, fontFamily: 'Helvetica-Bold' },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 0.5,
    borderTopColor: '#D4D0C8',
    paddingTop: 6,
  },
  footerText: { fontSize: 7, color: '#6B6B6B' },
})
